---
name: Release
on: # yamllint disable-line rule:truthy
  push:
    branches-ignore:
      - "**"
    tags:
      - "v*.*.*"
      # to be used by fork patch-releases ^^
      - "v*.*.*-*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x

      - name: Prepare
        id: prepare
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo tag_name=${TAG} >> $GITHUB_OUTPUT

      - name: Run GoReleaser

        env:
          PACKAGE_NAME: github.com/ksandr84on/nera
          GOLANG_CROSS_VERSION: v1.18.3
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.prepare.outputs.tag_name }}
